project_name: 'modeling-detr'
task: 'detection-detr'
num_classes: 10
n_epochs: 20
accelerator: 'gpu'
devices: '9'
monitor_metric: 'val_map_50'
box_detection_per_img: 100
optimizer: 'torch.optim.AdamW'
optimizer_kwargs:
  lr: 3e-4

scheduler: 'cosine_annealing_warmup.CosineAnnealingWarmupRestarts'
scheduler_kwargs:
  first_cycle_steps: 50
  cycle_mult: 1.0
  max_lr: 3e-4
  min_lr: 1e-5
  warmup_steps: 1
  gamma: 1.0
  last_epoch: -1

mlflow_config:
  run_name: 'detr'
  experiment_name: 'detr'
  tracking_uri: ''

data_config:
  data_path: ''
  batch_size: 8
  n_workers: 2
  image_size: 640
  processor_image_size: 640
  dataset_name: ''